"""Generate README.md from profile.toml: every image is a link to the widget server.

    python profile/readme.py                                   # writes README.md
    python profile/readme.py --base http://127.0.0.1:8000 --out SAMPLE.md   # local preview
"""

import argparse
import html
import tomllib
from pathlib import Path
from urllib.parse import quote, urlencode

ROOT = Path(__file__).resolve().parent.parent
CONFIG = tomllib.loads((ROOT / "profile" / "profile.toml").read_text())
WIDE_W = 806
# Cards that share a row are sized as a share of the column, so a row never wraps,
# whether the column is GitHub's 848px, a narrower editor preview, or a phone.
HALF, THIRD = "49%", "32.5%"


def url(base, widget, theme, params):
    items = []
    for key, value in params.items():
        for v in value if isinstance(value, (list, tuple)) else [value]:
            if v not in (None, ""):
                items.append((key, str(v)))
    items.append(("theme", theme))
    return f"{base}/api/{widget}?{urlencode(items, safe=',:|@', quote_via=quote)}"


def picture(base, widget, width, alt, href=None, **params):
    dark, light = (html.escape(url(base, widget, t, params)) for t in ("dark", "light"))
    img = (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{dark}" />'
           f'<img src="{light}" width="{width}" alt="{html.escape(alt)}" /></picture>')
    return f'<a href="{html.escape(href)}">{img}</a>' if href else img


def block(*parts):
    # One line per block: some previews (VS Code's, with breaks on) turn every newline
    # inside the HTML into a <br>, which splits rows and doubles the gaps between them.
    return '<p align="center">' + "<br/>".join(parts) + "</p>\n"


def rows(items, per_row):
    """Inline images, a space between cards and a line break between rows."""
    return "<br/>".join(" ".join(items[i:i + per_row]) for i in range(0, len(items), per_row))


def projects(base, key):
    s, login = CONFIG[key], CONFIG["login"]
    repos = s["repos"]
    header = picture(base, "section", WIDE_W, s["title"], title=s["title"],
                     caption=f'{s["caption"]} · {len(repos)} repos')
    layout = s.get("layout", "wide")
    if layout in ("wide", "cards"):
        width, per_row = (WIDE_W, 1) if layout == "wide" else (HALF, 2)
        cards = [picture(base, "repo", width, r["repo"], f'https://github.com/{login}/{r["repo"]}',
                         username=login, repo=r["repo"], size="wide" if layout == "wide" else None,
                         status=r.get("status"), description=r.get("description"), install=r.get("install"))
                 for r in repos]
        return block(header, rows(cards, per_row))
    params = {
        "username": login, "repos": ",".join(r["repo"] for r in repos), "layout": s["layout"],
        "status": [f'{r["repo"]}:{r["status"]}' for r in repos if r.get("status")],
        "describe": [f'{r["repo"]}:{r["description"]}' for r in repos if r.get("description")],
        "install": [f'{r["repo"]}:{r["install"]}' for r in repos if r.get("install")],
    }
    return block(header, picture(base, "repos", WIDE_W, s["title"],
                                            f"https://github.com/{login}?tab=repositories", **params))


def readme(base):
    c, login = CONFIG, CONFIG["login"]
    h, st, pubs, links = c["hero"], c["startup"], c["publications"], c["links"]
    out = ["<!-- Generated by profile/readme.py from profile/profile.toml. Edit that file, not this one. -->\n"]
    out.append(block(picture(base, "hero", 880, h["name"], name=h["name"], eyebrow=h["eyebrow"],
                             tags="|".join(h.get("tags", [])), line=h.get("line"))))
    out.append(block(rows([picture(base, "stats", HALF, "GitHub stats", username=login),
                           picture(base, "languages", HALF, "Top languages", username=login,
                                   skip=",".join(c["languages"]["skip"]))], 2),
                     picture(base, "commits", WIDE_W, "Commit graph", username=login)))
    out.append(projects(base, "open_source"))
    out.append(projects(base, "personal"))
    out.append(block(picture(base, "section", WIDE_W, st["title"], title=st["title"], caption=st["caption"]),
                     picture(base, "product", WIDE_W, st["name"], st["url"], name=st["name"], role=st["role"],
                             tagline=st["tagline"], audience=st["audience"], cta=st["cta"], image=st["screenshot"],
                             feature=[f'{f["icon"]}:{f["text"]}' for f in st["features"]])))
    out.append(block(picture(base, "section", WIDE_W, pubs["title"], title=pubs["title"],
                             caption=f'{pubs["caption"]} · {len(pubs["items"])} papers'),
                     rows([picture(base, "publication", WIDE_W, p["title"], p["url"], title=p["title"],
                                   venue=p["venue"], year=p["year"]) for p in pubs["items"]], 1)))
    out.append(block(picture(base, "section", WIDE_W, links["title"], title=links["title"],
                             caption=links["caption"]),
                     rows([picture(base, "link", THIRD, i["label"], i["url"], label=i["label"], value=i["value"],
                                   icon=i["icon"], hue=i["hue"]) for i in links["items"]], 3)))
    out.append(block(picture(base, "views", THIRD, "Profile views", username=login)))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default=CONFIG["service"], help="widget server origin")
    ap.add_argument("--out", default=str(ROOT / "README.md"))
    args = ap.parse_args()
    Path(args.out).write_text(readme(args.base.rstrip("/")))
    print(f"wrote {args.out} ({args.base})")


if __name__ == "__main__":
    main()
