"""Generate README.md from profile.toml: every image is a link to the widget server.

    python profile/readme.py                                   # writes README.md
    python profile/readme.py --base http://127.0.0.1:8000 --out SAMPLE.md   # local preview
"""

import argparse
import hashlib
import html
import tomllib
from pathlib import Path
from urllib.parse import quote, urlencode

ROOT = Path(__file__).resolve().parent.parent
CONFIG = tomllib.loads((ROOT / "profile" / "profile.toml").read_text())
WIDE = "100%"  # full-width cards span the column, so their edges line up with the pairs
# Cards that share a row are sized as a share of the column, so a row never wraps,
# whether the column is GitHub's 848px, a narrower editor preview, or a phone.
# 47%, not 50%: GitHub pads left/right-aligned images by 20px, and a pair must still fit.
HALF = "47%"


def widget_version():
    """A short hash of the widget code and assets. It goes into every image URL, so a
    design change is a new URL and no cache (GitHub's image proxy, an editor) keeps an old one."""
    digest = hashlib.sha256()
    for path in sorted((ROOT / "widgets").rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts:
            digest.update(path.relative_to(ROOT).as_posix().encode())
            digest.update(path.read_bytes())
    return digest.hexdigest()[:8]


VERSION = widget_version()


def url(base, widget, theme, params):
    items = []
    for key, value in params.items():
        for v in value if isinstance(value, (list, tuple)) else [value]:
            if v not in (None, ""):
                items.append((key, str(v)))
    items += [("theme", theme), ("v", VERSION)]
    # Commas stay encoded: srcset splits on them, which would cut a dark-mode URL in two.
    return f"{base}/api/{widget}?{urlencode(items, safe=':|@', quote_via=quote)}"


def picture(base, widget, width, alt, href=None, align=None, **params):
    dark, light = (html.escape(url(base, widget, t, params)) for t in ("dark", "light"))
    side = f' align="{align}"' if align else ""
    img = (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{dark}" />'
           f'<img src="{light}" width="{width}"{side} alt="{html.escape(alt)}" /></picture>')
    return f'<a href="{html.escape(href)}">{img}</a>' if href else img


def block(*parts):
    # One line per block: some previews turn every newline inside HTML into a <br>.
    return '<p align="center">' + "".join(parts) + "</p>\n"


def row(cards):
    """Two cards on one row. They float (align=left, then right) rather than sit inline,
    so the row holds even where a stylesheet forces images to display:block (some editor
    previews do); each pair meets both edges. A clearing break ends the row."""
    sides = ["left", "right"][:len(cards)] if len(cards) > 1 else [None]
    return "".join(card(side) for card, side in zip(cards, sides)) + '<br clear="all"/>'


def pairs(cards):
    return "".join(row(cards[i:i + 2]) for i in range(0, len(cards), 2))


def projects(base, key):
    s, login = CONFIG[key], CONFIG["login"]
    repos = s["repos"]
    header = picture(base, "section", WIDE, s["title"], title=s["title"],
                     caption=f'{s["caption"]} · {len(repos)} repos')
    layout = s.get("layout", "wide")

    def card(r, width, **extra):
        return lambda side: picture(base, "repo", width, r["repo"], f'https://github.com/{login}/{r["repo"]}',
                                    align=side, username=login, repo=r["repo"], status=r.get("status"),
                                    description=r.get("description"), install=r.get("install"), **extra)

    if layout == "wide":
        return block(header, "".join(card(r, WIDE, size="wide")(None) for r in repos))
    if layout == "cards":
        return block(header, pairs([card(r, HALF) for r in repos]))
    params = {
        "username": login, "repos": ",".join(r["repo"] for r in repos), "layout": layout,
        "status": [f'{r["repo"]}:{r["status"]}' for r in repos if r.get("status")],
        "describe": [f'{r["repo"]}:{r["description"]}' for r in repos if r.get("description")],
        "install": [f'{r["repo"]}:{r["install"]}' for r in repos if r.get("install")],
    }
    return block(header, picture(base, "repos", WIDE, s["title"], f"https://github.com/{login}?tab=repositories",
                                 **params))


def readme(base):
    c, login = CONFIG, CONFIG["login"]
    h, st, pubs, links = c["hero"], c["startup"], c["publications"], c["links"]
    out = ["<!-- Generated by profile/readme.py from profile/profile.toml. Edit that file, not this one. -->\n"]
    out.append(block(picture(base, "hero", WIDE, h["name"], name=h["name"], eyebrow=h["eyebrow"],
                             tags="|".join(h.get("tags", [])), line=h.get("line"))))
    skip = ",".join(c["languages"]["skip"])
    out.append(block(row([lambda side: picture(base, "stats", HALF, "GitHub stats", align=side, username=login),
                          lambda side: picture(base, "languages", HALF, "Top languages", align=side,
                                               username=login, skip=skip)]),
                     picture(base, "commits", WIDE, "Commit graph", username=login)))
    out.append(projects(base, "open_source"))
    out.append(projects(base, "personal"))
    out.append(block(picture(base, "section", WIDE, st["title"], title=st["title"], caption=st["caption"]),
                     picture(base, "product", WIDE, st["name"], st["url"], name=st["name"], role=st["role"],
                             tagline=st["tagline"], audience=st["audience"], cta=st["cta"], image=st["screenshot"],
                             feature=[f'{f["icon"]}:{f["text"]}' for f in st["features"]])))
    # Full-width cards need no breaks: on GitHub each wraps onto its own line anyway.
    out.append(block(picture(base, "section", WIDE, pubs["title"], title=pubs["title"],
                             caption=f'{pubs["caption"]} · {len(pubs["items"])} papers'),
                     "".join(picture(base, "publication", WIDE, p["title"], p["url"], title=p["title"],
                                     venue=p["venue"], year=p["year"]) for p in pubs["items"])))
    # Links and the view counter share one grid of pairs.
    contacts = [(lambda i: lambda side: picture(base, "link", HALF, i["label"], i["url"], align=side,
                                                label=i["label"], value=i["value"], icon=i["icon"],
                                                hue=i["hue"]))(i) for i in links["items"]]
    contacts.append(lambda side: picture(base, "views", HALF, "Profile views", align=side, username=login))
    out.append(block(picture(base, "section", WIDE, links["title"], title=links["title"], caption=links["caption"]),
                     pairs(contacts)))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default=CONFIG["service"], help="widget server origin")
    ap.add_argument("--out", default=str(ROOT / "README.md"))
    args = ap.parse_args()
    Path(args.out).write_text(readme(args.base.rstrip("/")))
    print(f"wrote {args.out} ({args.base})")


if __name__ == "__main__":
    main()
